### ISSUE TITLE
[2주차 학습] 4장 아키텍쳐 나머지 학습 내용 정리

### ISSUE THREAD

**Issue by leejohy-0223** [leejohy-0223/Database-Study#4]
기간 : 2022.05.11 ~ 2022.05.17
학습 범위 : P98 ~ P153

**Comment by leejohy-0223** [comment]
[InnoDB 스토리지 엔진 아키텍처 1](https://new-age-jh.tistory.com/286)
[InnoDB 스토리지 엔진 아키텍처 2](https://new-age-jh.tistory.com/289)
[버퍼 풀과 주변 기능](https://new-age-jh.tistory.com/288)

**Comment by CMSSKKK** [comment]
https://velog.io/@cmsskkk/realmysql42

**Comment by devjun10** [comment]
[2주차 학습정리](https://knowing-lemon-7bd.notion.site/2-a03e609410534136a71584ea93d3b5c6)

**Comment by jinan159** [comment]
[2주차 학습정리](https://jwkim96.tistory.com/261)
